#!/bin/bash
# YC 頻道批次處理腳本

WORK_DIR=~/.openclaw/workspace/research/youtube_summaries
YT_DLP=/tmp/yt-dlp-new
GEMINI_API_KEY="AIzaSyApwdWgaITpJHZ2PXuB3UxpnrwSSnCApZ8"
OUTPUT_DIR="$WORK_DIR/youtubers/ycombinator"

# 已處理的影片 ID
SKIP_IDS="qwmmWzPnhog cqrJzG03ENE YFeb3yAxtjE lWmDiDGsLK4 l0h3nAW13ao"

# 待處理影片列表
VIDEOS=(
"4uzGDAoNOZc|OpenClaw Creator: Why 80% Of Apps Will Disappear"
"K5JoLAauzq4|How We Redesigned Our Website"
"leQ89XSHILw|Why Your Startup Website Isn't Converting"
"dC_3ys349bU|The ML Technique Every Founder Should Know"
"0kARDVL2nZg|How To Get Your First Users"
"2hgjgycOU_0|Inside The Startup Building Reusable Rockets"
"pBlIgs6w7Ss|How Intelligent Is AI, Really?"
"5WN8bfG06Hk|From Pivot Hell To $1.4 Billion Unicorn"
"t8co94HS6tY|How Amplitude Went From Skeptics to All In on AI"
"Z4L4ZqL1xqQ|The Best Consumer Startup Ideas Were Impossible Until Now"
"RynySryqM_0|Cursor Head of Design Roasts Startup Websites"
"KTmxaMdUbHA|AI Is Eating Logistics"
"hKw6cRKcqzY|Inside The Startup Launching AI Data Centers Into Space"
"i_PjjXKNpA4|The Startup Playbook for Hiring Your First Engineers and AEs"
"DULfEcPR0Gc|Good News For Startups: Enterprise Is Bad At AI"
"JZLZQVmfGn8|Transformers Explained: The Discovery That Changed AI Forever"
"nGLmpKi-jRU|Startup Advice: AI GTM, Pivoting & How To Hire"
"Hm-ZIiwiN1o|Billion-Dollar Unpopular Startup Ideas"
"IqwSb2hO1jE|What Everyone Is Getting Wrong About AI And Jobs"
"ENG_DQF5E60|This Startup Is Trying To Delete 29% Of All CO2 Emissions"
"DJjZzzPANBY|Ask These Questions Before Starting An AI Startup"
"bxBzsSsqQAM|The 7 Most Powerful Moats For AI Startups"
"Pdne9xaRLUc|Why Now Is The Best Time To Build In Crypto"
"uqc_vt95GJg|Aaron Levie: Why Startups Win In The AI Era"
"Zyw-YA0k3xo|The FDE Playbook for AI Startups with Bob McGrew"
"TrXi3naD6Og|Michael Truell: Building Cursor At 23, Taking On GitHub Copilot"
"raTbhtKZTZA|OpenAI vs. Deepseek vs. Qwen: Comparing Open Source LLM Architectures"
"pHuXCzM2ntU|How This 25-Year-Old Built A $675M Legal AI Startup"
"JdT78t1Offo|Anthropic Co-founder: Building Claude Code, Lessons From GPT-3"
"DH7REvnQ1y4|The Sales Playbook For Founders"
"-7Qz7tSTfUU|Dylan Field: Scaling Figma and the Future of Design"
"lqokpIme47A|The Finance Startup Bringing Agentic AI to Wall Street"
"p8Jx4qvDoSo|Scaling and the Road to Human-Level AI"
"uEeFsW9343g|Brand Design Tips From Linear Founder Karri Saarinen"
"a8-QsBHoH94|Chelsea Finn: Building Robots That Can Do Anything"
"kOyIjt6FUrw|How Replit Went From $10M to $100M ARR In Just 9 Months"
"2Yguz5U-Nic|Nobel Laureate John Jumper: AI is Revolutionizing Scientific Discovery"
"2jOnoTEk-xA|Aravind Srinivas: Perplexity's Race to Build Agentic Search"
"RNJCfif1dPY|Andrew Ng: Building Faster with AI"
"ShYKkPPhOoc|How to Spend Your 20s in the AI Era"
"5QcCeSsNRks|François Chollet: How We Get To AGI"
"_PioN-CpOP0|Fei-Fei Li: Spatial Intelligence is the Next Frontier in AI"
"xFQ5mIJdxhA|Legendary Consumer VC Predicts The Future Of AI Products"
"AUUZuzVHKdo|Satya Nadella: Microsoft's AI Bets, Hyperscaling, Quantum Computing"
"V979Wd1gmTU|Sam Altman: The Future of OpenAI, ChatGPT's Origins"
"cFIlta1GkiE|Elon Musk: Digital Superintelligence, Multiplanetary Life"
"LCEmiRjPEtQ|Andrej Karpathy: Software Is Changing (Again)"
"5noIKN8t69U|Alexandr Wang: Building Scale AI, Transforming Work With Agents"
"oOylEw3tPQ8|Cursor CEO: Going Beyond Code, Superintelligent AI Agents"
"XdigD0LOXx0|Fusion Energy Will Power the AI Boom"
"DL82mGde6wo|State-Of-The-Art Prompting For AI Agents"
"WJoZK9sMwvw|How To Design Better AI Apps"
"K4s6Cgicw_A|Startup Ideas You Can Now Build With AI"
"TECDj4JUx7o|How AI Coding Agents Will Change Your Job"
"LKgAx7FWva4|Windsurf CEO: Betting On AI Agents, Pivoting In 48 Hours"
"BJjsfNO5JTo|How To Get The Most Out Of Vibe Coding"
"aYK0H85E_oU|How Zepto Became India's Fastest Growing Startup"
"JOYSDqJdiro|The Next Breakthrough In AI Agents Is Here"
"VIkphkYlkaQ|How To Build A Truly Abundant Future"
"ksGNfd-wQY4|What Founders Can Do To Improve Their Design Game"
"3N3TnaViyjk|DoorDash CEO: Customer Obsession, Surviving Startup Death"
"bvjyaz4ZiVI|How Top 1% Founders Navigate Co-founder Conflict"
"VaQA55ZZWBU|From A Pivot To Building A $9.6 Billion Payroll Company"
"4UE4e6b2qtA|Figma's Dylan Field: Exploring the idea maze, vibe coding"
"5uBAQrg4SoQ|GPT-4.5 = Big Model Energy"
"IACHfKmZMr8|Vibe Coding Is The Future"
"DBhSfROq3wU|AI Interfaces Of The Future"
"SP7Ua8FKZN4|How To Build The Future: Aravind Srinivas"
"aIKfA3gIXwo|How AI Is Changing Enterprise"
"sOFmYwYa9Pk|How Blake Scholl Built The First Independent Supersonic Jet"
"IRROi-Q1V44|The Right (And Wrong) Way To Spend Money At Your Startup"
"TANaRNMbYgk|How To Get AI Startup Ideas"
"4Tmn-XP93m4|The Engineering Unlocks Behind DeepSeek"
"eW7rUtYHD9U|Bob McGrew: AI Agents And The Path To AGI"
"0LMK5JYkB94|AI Revolution: What Nobody Else Is Seeing"
"d6Ed5bZAtrM|How Scaling Laws Will Determine AI's Future"
"7Kt9ugD3bGQ|How To Use AI In Your Startup"
"FwD0wqwUjAI|How To Build The Future: Parker Conrad"
"rjyJsbUunQ4|Building A $2 Billion SaaS Company: Lessons From A Two Time Founder"
"uGjv25IrjoE|The Lightcone 2025 Forecast"
"CcnwFJqEnxU|How David Lieb Turned a Failing Startup Into Google Photos"
"z0wt2pe_LZM|2024: The Year the GPT Wrapper Myth Proved Wrong"
"VDmU0jjklBo|Anthropic's Claude Computer Use Is A Game Changer"
"z1aKRhRnVNk|How To Start A Dev Tools Company"
"ASABxNenD_U|Vertical AI Agents Could Be 10X Bigger Than SaaS"
"EW9TUqOgjmQ|Twitter vs. X: Product Lessons For Startup Founders"
"JiwiqYGw4iU|Why The Next AI Breakthroughs Will Be In Reasoning, Not Scaling"
"xXCBz_8hM9w|How To Build The Future: Sam Altman"
"lbJilIQhHko|The 10 Trillion Parameter AI Model With 300 IQ"
"Q0Xs0lGgwVA|You Don't Have To Be A Billionaire To Launch Satellites"
"Lv9bKyQgoHo|Why OpenAI's o1 Is A Huge Deal"
"wH3TKpALlw4|Starting A Company? The Key Terms You Should Know"
"jbIQfoldLag|Now Anyone Can Code: How AI Agents Can Build Your Whole App"
"CKfERe55CeA|Why Design Matters: Lessons from Stripe, Lyft and Airbnb"
"HB3l1BPi7zo|How Do Billion Dollar Startups Start?"
)

echo "共 ${#VIDEOS[@]} 支影片待處理"
